config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users
  root 'pages#home'
  
  resources :recipes do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :recipes
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all.reverse_order
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    recipe = Recipe.find(params[:recipe_id])
    @comment = recipe.comments.build
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    recipe = Recipe.find(params[:recipe_id])
    @comment = recipe.comments.create(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to(@comment.recipe, :notice =>'Comment was successfully created.')}
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :user_id, :recipe_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all.reverse_order
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    recipe = Recipe.find(params[:id])
    @comments = recipe.comments.reverse_order
  end

  # GET /recipes/new
  def new
    @recipe = current_user.recipes.build
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = current_user.recipes.create(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :body, :ingredients, :category, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/comments/_form.html.erb
<%= form_for([@comment.recipe, @comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br>
  
  <div class="form-group">
    <h4>Write you comment here:</h4>
    <%= form.text_area :body, class: "form-control input-lg", placeholder: "Comment" %>
  </div>
  
  <div class="form-group">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="container">

<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

</div>

app/views/comments/index.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th>Recipe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= comment.recipe %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

</div>

app/views/comments/new.html.erb
<div class="container">

<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

</div>

app/views/comments/show.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Recipe:</strong>
  <%= @comment.recipe %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>


<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @recipe.body %>
</p>

<p>
  <strong>Category:</strong>
  <%= @recipe.category %>
</p>

<p>
  <strong>User:</strong>
  <%= @recipe.user %>
</p>

<%= link_to 'Give a comment', new_recipe_comment_path(@question) %>
  <% @comments.each do |comment| %>
    <h4><%= comment.body %> posted by <%= comment.user.email %></h4>
  <% end %>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipicker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <div class="footer" >
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<header class="header-image">
    <div class="headline">
        <div class="container">
            <h1>Recipicker</h1>
            <p>This website helps you decide what recipe to make by showing you recipes that match the groceries you have in your fridge at this very moment. 
            <br>Just plot in your ingredeants in the search field and enjoy!</p>
            <% if(!user_signed_in?) %>
            <p>Sign in to see and post recipes</p>
            <% else %>
            <%= link_to 'Post a recipe', new_recipe_path, class: 'btn btn-primary btn-lg' %>
            <%= link_to 'See all recipes', recipes_path, class: 'btn btn-primary btn-lg' %>
            <% end %>
        </div>
    </div>
</header>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <br>
  
  <div class="form-group">
    <h4>Wrtie the title of your recipe here:</h4>
    <%= form.text_field :title, class: "form-control input-lg", placeholder: "F.eks Pizza" %>
  </div>

<br>

  <div class="form-group">
    <h4>Write the recipe here:</h4>
    <%= form.text_area :body, class: "form-control input-lg", placeholder: "F.eks. Do this, then do this." %>
  </div>

<br>

  <div class="form-group">
    <h4>Write the ingredients you need for the recipe here:</h4>
    <%= form.text_field :ingredients, class: "form-control input-lg", placeholder: "F.eks. Dough, Sause, Cheese" %>
  </div>

<br>

  <div class="form-group">
    <h4>Chose a category for the recipe here:</h4>
    <%= form.text_field :category, class: "form-control input-lg", placeholder: "F.eks. Italian" %>
  </div>

<br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<div class="container">

<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

</div>

app/views/recipes/index.html.erb
<div class="container">

<center>

<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<br>
  
<% @recipes.each do |recipe| %>
   <div class="jumbotron" style="max-width: 800px">
     <h2><%= recipe.title %></h2>
     <p><%= recipe.category %></p>
     <p><%= recipe.body %></p>
     <p><%= recipe.ingredients %></p>
     <h5>Posted by <%= recipe.user.email %></h5>
     <div class="change_recipe">
       <%= link_to 'Show', recipe, class: "btn btn-primary btn-sm" %>
       <%= link_to 'Edit', edit_recipe_path(recipe), class: "btn btn-primary btn-sm" %>
       <%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary btn-sm" %>
       <%= link_to 'Comment', new_recipe_comment_path(recipe), class: "btn btn-primary btn-sm" %>
     </div>
  </div>
<% end %>


<br>

<%= link_to 'New Recipe', new_recipe_path %>

</center>

</div>

app/views/recipes/new.html.erb
<div class="container">
    
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

</div>

app/views/recipes/show.html.erb
<div class="container">
  
<center>
  
<p id="notice"><%= notice %></p>


<div class="jumbotron" style="max-width: 800px">
     <h2><%= @recipe.title %></h2>
     <p><%= @recipe.category %></p>
     <p><%= @recipe.body %></p>
     <p><%= @recipe.ingredients %></p>
     <h5>Posted by <%= @recipe.user.email %></h5>
     <div class="change_recipe">
       <%= link_to 'Show', @recipe, class: "btn btn-primary btn-sm" %>
       <%= link_to 'Edit', edit_recipe_path(@recipe), class: "btn btn-primary btn-sm" %>
       <%= link_to 'Destroy', @recipe, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary btn-sm" %>
       <%= link_to 'Post a Comment', new_recipe_comment_path(@recipe), class: "btn btn-primary btn-sm" %>
       
       <br><br>
       
       <h4>Comments to this recipe:</h4>
       <% @comments.each do |comment| %>
       <h5><%= comment.body %> posted by <%= comment.user.email %></h5>
  <% end %>
     </div>

</center>

</div>
     

app/views/shared/_footer.html.erb
<hr>© Copyrigth Juni W. Bjerde 2017

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Recipicker', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if(!user_signed_in?) %>
          <li>
            <%= link_to 'Sign Up', new_user_registration_path %>
          </li>
          <li>
            <%= link_to 'Log In', new_user_session_path %>
          </li>
        <% else %>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Options <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li><%= link_to "Main site", root_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "All recipes", recipes_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Post a new recipe', new_recipe_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>